#include "Cube/JourneyMatterhorn.h"

#include "MuseeVision.h"
#include "Cube/ElanJourney.h"
#include "Cube/CubeMesh.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "AssetRegistry/IAssetRegistry.h"
#include "Components/ExponentialHeightFogComponent.h"
#include "Components/VolumetricCloudComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Engine/StaticMesh.h"
#include "Materials/MaterialInterface.h"
#include "Misc/PackageName.h"
#include "ProceduralMeshComponent.h"
#include "Components/InstancedStaticMeshComponent.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Math/RandomStream.h"
#include "HAL/IConsoleManager.h"
#include "Kismet/KismetMaterialLibrary.h"
#include "Materials/MaterialParameterCollection.h"

// Generated by Scripts/journey_terrain.py cpp from terrain.json: the places, the lake's outline.
#include "Cube/MatterhornData.inl"

namespace
{
	const TCHAR* const TerrainPath = TEXT("/Game/Museum/Journeys/Matterhorn/Terrain");
	const TCHAR* const ReadyPath = TEXT("/Game/Museum/Journeys/Matterhorn/Ready");
}

bool UJourneyMatterhorn::IsAvailable() const
{
	return FPackageName::DoesPackageExist(ReadyPath);
}

const UJourneyMatterhorn::FView& UJourneyMatterhorn::View(int32 Index)
{
	static TArray<FView> Views;
	if (Views.IsEmpty())
	{
		auto Find = [](const TCHAR* Key) -> FView
		{
			for (const MatterhornData::FPlaceData& P : MatterhornData::Places)
			{
				if (FCString::Strcmp(P.Key, Key) == 0) { return FView{P.E, P.N, P.Floor, true}; }
			}
			return FView();
		};
		Views = {Find(TEXT("riffelsee")), Find(TEXT("glacier")), Find(TEXT("hornli")), Find(TEXT("solvay")), Find(TEXT("summit")), Find(TEXT("summit"))};
		Views[1].bLand = false;   // inside the crevasse: its own ice all round
	}
	return Views[FMath::Clamp(Index, 0, Views.Num() - 1)];
}

void UJourneyMatterhorn::Setup(AElanJourney* InDirector)
{
	Super::Setup(InDirector);
	// Lumen's far-field tracing (to 10 km): reflections and bounce from the land beyond the near field.
	if (IConsoleVariable* Far = IConsoleManager::Get().FindConsoleVariable(TEXT("r.LumenScene.FarField")))
	{
		FarFieldWas = Far->GetInt();
		if (FarFieldWas != 1) { Far->Set(1, ECVF_SetByCode); }
	}
	BuildLand();
	BuildLake();
	BuildRidge();
	BuildBoulders();
	// The flakes (the engine's 1 m plane, scaled to a few millimetres), round the eyes.
	Flakes = Make<UInstancedStaticMeshComponent>(TEXT("Flakes"), true);
	Flakes->SetStaticMesh(LoadObject<UStaticMesh>(nullptr, TEXT("/Engine/BasicShapes/Plane.Plane")));
	Flakes->SetMaterial(0, LoadObject<UMaterialInterface>(nullptr, TEXT("/Game/Museum/Journeys/Matterhorn/Materials/M_MH_Flake.M_MH_Flake")));
	Flakes->SetCollisionEnabled(ECollisionEnabled::NoCollision);
	Flakes->SetCastShadow(false);
	{
		FRandomStream R(1449);
		TArray<FTransform> Start;
		for (int32 i = 0; i < 6000; ++i)
		{
			FlakeState.Add(FVector4(R.FRandRange(-8.0, 8.0), R.FRandRange(-8.0, 8.0), R.FRandRange(-8.0, 8.0), R.FRand()));
			Start.Add(FTransform(FRotator::ZeroRotator, FVector::ZeroVector, FVector(0.0)));
		}
		Flakes->AddInstances(Start, false);
		Flakes->SetVisibility(false);
	}
}

void UJourneyMatterhorn::BuildLand()
{
	Pivot = Make<USceneComponent>(TEXT("LandPivot"), true);
	Land = NewObject<USceneComponent>(Director, MakeUniqueObjectName(Director, USceneComponent::StaticClass(), TEXT("Land")));
	Land->SetMobility(EComponentMobility::Movable);
	Land->SetupAttachment(Pivot);
	Land->RegisterComponent();
	JourneyParts.Add(Land);

	// Every tile in the terrain folder: SM_<tile>__<west>_<north>, its origin the tile's north-west corner (LV95 metres).
	IAssetRegistry& Registry = FModuleManager::LoadModuleChecked<FAssetRegistryModule>(TEXT("AssetRegistry")).Get();
	TArray<FAssetData> Assets;
	Registry.GetAssetsByPath(FName(TerrainPath), Assets, false);
	int32 Made = 0;
	for (const FAssetData& A : Assets)
	{
		const FString Name = A.AssetName.ToString();
		FString Left, Coords, West, North;
		if (!Name.Split(TEXT("__"), &Left, &Coords) || !Coords.Split(TEXT("_"), &West, &North)) { continue; }
		UStaticMesh* Mesh = Cast<UStaticMesh>(A.GetAsset());
		if (!Mesh) { continue; }
		UStaticMeshComponent* C = NewObject<UStaticMeshComponent>(Director, MakeUniqueObjectName(Director, UStaticMeshComponent::StaticClass(), FName(*Name)));
		C->SetMobility(EComponentMobility::Movable);
		C->SetupAttachment(Land);
		C->SetStaticMesh(Mesh);
		C->SetCollisionEnabled(ECollisionEnabled::NoCollision);
		C->SetRelativeLocation(FVector(FCString::Atod(*West) * 100.0, -FCString::Atod(*North) * 100.0, 0.0));
		C->bCastFarShadow = true;
		C->bRayTracingFarField = true;   // Lumen's far field: the mountain 8 km away in Riffelsee's mirror (near tiles: PlaceLand)
		C->RegisterComponent();
		JourneyParts.Add(C);
		Tiles.Add(C);
		++Made;
	}
	UE_LOG(LogMusee, Log, TEXT("Matterhorn: %d land tiles."), Made);
	// The huts and the summit cross, on the land where they stand.
	for (const MatterhornData::FBuildingData& B : MatterhornData::Buildings)
	{
		const FString Key(B.Key);
		const FString Name = Key == TEXT("hornli") ? TEXT("SM_MH_HornliHut") : (Key == TEXT("cross") ? TEXT("SM_MH_SummitCross") : TEXT("SM_MH_SolvayHut"));
		UStaticMesh* Mesh = LoadObject<UStaticMesh>(nullptr, *FString::Printf(TEXT("/Game/Museum/Journeys/Matterhorn/Things/%s.%s"), *Name, *Name));
		if (!Mesh) { continue; }
		UStaticMeshComponent* C = NewObject<UStaticMeshComponent>(Director, MakeUniqueObjectName(Director, UStaticMeshComponent::StaticClass(), FName(*Name)));
		C->SetMobility(EComponentMobility::Movable);
		C->SetupAttachment(Land);
		C->SetStaticMesh(Mesh);
		C->SetCollisionEnabled(ECollisionEnabled::NoCollision);
		C->SetRelativeLocationAndRotation(FVector(B.E * 100.0, -B.N * 100.0, B.Z * 100.0), FRotator(0.0, B.Bearing - 90.0, 0.0));
		C->RegisterComponent();
		JourneyParts.Add(C);
	}
}

void UJourneyMatterhorn::BuildBoulders()
{
	// The boulders round the places (journey_terrain.py: on rock, scree and meadow, never on snow or in the lake): six
	// shapes of gneiss (1 unit about 2 m long), each placed at its size, yawed, tipped a little, its foot in the ground.
	TArray<UInstancedStaticMeshComponent*> Kinds;
	for (int32 k = 0; k < 6; ++k)
	{
		UStaticMesh* Mesh = LoadObject<UStaticMesh>(nullptr, *FString::Printf(TEXT("/Game/Museum/Journeys/Matterhorn/Things/SM_MH_Boulder%d.SM_MH_Boulder%d"), k, k));
		UInstancedStaticMeshComponent* I = Mesh ? NewObject<UInstancedStaticMeshComponent>(Director, MakeUniqueObjectName(Director, UInstancedStaticMeshComponent::StaticClass(), TEXT("Boulders"))) : nullptr;
		if (I)
		{
			I->SetMobility(EComponentMobility::Movable);
			I->SetupAttachment(Land);
			I->SetStaticMesh(Mesh);
			I->SetCollisionEnabled(ECollisionEnabled::NoCollision);
			I->RegisterComponent();
			JourneyParts.Add(I);
		}
		Kinds.Add(I);
	}
	FRandomStream R(4478);
	for (const MatterhornData::FBoulderData& B : MatterhornData::Boulders)
	{
		if (UInstancedStaticMeshComponent* I = Kinds[FMath::Clamp(B.Shape, 0, 5)])
		{
			const double S = B.Size * 0.5;
			const FRotator Rot(R.FRandRange(-8.f, 8.f), B.Yaw, R.FRandRange(-8.f, 8.f));
			I->AddInstance(FTransform(Rot, FVector(B.E * 100.0, -B.N * 100.0, B.Z * 100.0 - S * 8.0), FVector(S)), false);
		}
	}
}

void UJourneyMatterhorn::BuildRidge()
{
	const int32 NC = UE_ARRAY_COUNT(MatterhornData::Crest);
	auto CrestAt = [NC](int32 i) { i = FMath::Clamp(i, 0, NC - 1); return FVector(MatterhornData::Crest[i][0], MatterhornData::Crest[i][1], MatterhornData::Crest[i][2]); };
	// The land's frame: LV95 (E, N) to Unreal (x east, y south).
	auto ToLand = [](const FVector& P) { return FVector(P.X * 100.0, -P.Y * 100.0, P.Z * 100.0); };
	// Rope teams on the crest, climbing: two above the hut, three at mid-height, two just above the Solvay hut.
	struct FTeam { int32 First; TArray<int32> Gaps; int32 Jacket; };
	const FTeam Teams[] = {{55, {2}, 0}, {63, {2, 3}, 1}, {205, {2, 2}, 2}, {372, {3}, 0}, {585, {2}, 1}};
	TArray<UInstancedStaticMeshComponent*> Climbers;
	for (int32 k = 0; k < 3; ++k)
	{
		UStaticMesh* Mesh = LoadObject<UStaticMesh>(nullptr, *FString::Printf(TEXT("/Game/Museum/Journeys/Matterhorn/Things/SM_MH_Climber%d.SM_MH_Climber%d"), k, k));
		UInstancedStaticMeshComponent* I = Mesh ? NewObject<UInstancedStaticMeshComponent>(Director, MakeUniqueObjectName(Director, UInstancedStaticMeshComponent::StaticClass(), TEXT("Climbers"))) : nullptr;
		if (I)
		{
			I->SetMobility(EComponentMobility::Movable);
			I->SetupAttachment(Land);
			I->SetStaticMesh(Mesh);
			I->SetCollisionEnabled(ECollisionEnabled::NoCollision);
			I->RegisterComponent();
			JourneyParts.Add(I);
		}
		Climbers.Add(I);
	}
	for (const FTeam& T : Teams)
	{
		int32 i = T.First;
		TArray<int32> At = {i};
		for (const int32 G : T.Gaps) { i += G; At.Add(i); }
		for (int32 m = 0; m < At.Num(); ++m)
		{
			const FVector P = CrestAt(At[m]), Next = CrestAt(At[m] + 1);
			const FVector Dir = Next - P;
			const double Yaw = FMath::RadiansToDegrees(FMath::Atan2(-Dir.Y, Dir.X));   // Unreal's y runs south
			if (UInstancedStaticMeshComponent* I = Climbers[(T.Jacket + m) % 3])
			{
				I->AddInstance(FTransform(FRotator(0, Yaw, 0), ToLand(P - FVector(0, 0, 0.05))), false);
			}
		}
	}
	// The fixed rope by the Solvay hut: along the crest's east side, 60 cm off it and 35 cm over the rock, on bolts
	// every 6 m, sagging between.
	{
		const FVector2D Car(View(3).E, View(3).N);
		CubeMesh::FMesh Rope;
		const FVector Origin = ToLand(CrestAt(552));   // the mesh's own origin (its vertices near it, in floats)
		auto Local = [&](const FVector& P) { return (ToLand(P) - Origin) / 100.0; };
		TArray<FVector> Pts;
		for (int32 i = 552; i <= 606; ++i)
		{
			const FVector P = CrestAt(i), Q = CrestAt(i + 1);
			FVector2D U = FVector2D(Q.X - P.X, Q.Y - P.Y).GetSafeNormal();
			FVector2D Side(-U.Y, U.X);
			if (FVector2D::DotProduct(Side, Car - FVector2D(P.X, P.Y)) < 0) { Side = -Side; }
			const double Sag = 0.18 * FMath::Sin(UE_DOUBLE_PI * ((i - 552) % 3) / 3.0);
			Pts.Add(FVector(P.X + Side.X * 0.6, P.Y + Side.Y * 0.6, P.Z + 0.35 - Sag));
			if ((i - 552) % 3 == 0)
			{
				// A bolt and its ring.
				const FVector B(P.X + Side.X * 0.6, P.Y + Side.Y * 0.6, P.Z + 0.35);
				CubeMesh::Rod(Rope, Local(B), Local(B - FVector(0, 0, 0.3)), 0.012, 6);
			}
		}
		for (int32 i = 0; i + 1 < Pts.Num(); ++i) { CubeMesh::Rod(Rope, Local(Pts[i]), Local(Pts[i + 1]), 0.014, 8, false); }
		UProceduralMeshComponent* R = NewObject<UProceduralMeshComponent>(Director, MakeUniqueObjectName(Director, UProceduralMeshComponent::StaticClass(), TEXT("FixedRope")));
		R->SetMobility(EComponentMobility::Movable);
		R->SetupAttachment(Land);
		R->SetCollisionEnabled(ECollisionEnabled::NoCollision);
		R->SetRelativeLocation(Origin);
		R->RegisterComponent();
		Rope.Write(R, 0, false);
		R->SetMaterial(0, LoadObject<UMaterialInterface>(nullptr, TEXT("/Game/Museum/Journeys/Matterhorn/Materials/MI_MH_Rope.MI_MH_Rope")));
		JourneyParts.Add(R);
	}
	// Zermatt's lights (shown at night).
	{
		UStaticMesh* Sphere = LoadObject<UStaticMesh>(nullptr, TEXT("/Engine/BasicShapes/Sphere.Sphere"));
		Lamps = NewObject<UInstancedStaticMeshComponent>(Director, MakeUniqueObjectName(Director, UInstancedStaticMeshComponent::StaticClass(), TEXT("ZermattLights")));
		Lamps->SetMobility(EComponentMobility::Movable);
		Lamps->SetupAttachment(Land);
		Lamps->SetStaticMesh(Sphere);
		Lamps->SetCollisionEnabled(ECollisionEnabled::NoCollision);
		Lamps->SetCastShadow(false);
		Lamps->RegisterComponent();
		if (UMaterialInterface* M = LoadObject<UMaterialInterface>(nullptr, TEXT("/Game/Museum/Journeys/Matterhorn/Materials/M_MH_Lamp.M_MH_Lamp")))
		{
			LampGlow = UMaterialInstanceDynamic::Create(M, Director);
			Lamps->SetMaterial(0, LampGlow);
		}
		FRandomStream R(1600);
		for (const auto& L : MatterhornData::Lights)
		{
			const double S = R.FRandRange(1.4, 3.0);   // the engine's sphere is 1 m across: 1.4–3 m of glow
			Lamps->AddInstance(FTransform(FRotator::ZeroRotator, ToLand(FVector(L[0], L[1], L[2])), FVector(S)), false);
		}
		Lamps->SetVisibility(false);
		JourneyParts.Add(Lamps);
	}
}

void UJourneyMatterhorn::MoveFlakes(float DeltaSeconds, float Amount, const FVector& Wind)
{
	if (!Flakes) { return; }
	const int32 Shown = FMath::Clamp(int32(Amount * FlakeState.Num()), 0, FlakeState.Num());
	Flakes->SetVisibility(Shown > 0);
	if (Shown == 0) { return; }
	TArray<FTransform> Out;
	Out.SetNum(FlakeState.Num());
	for (int32 i = 0; i < FlakeState.Num(); ++i)
	{
		FVector4& F = FlakeState[i];
		const double R = F.W;
		// Fall at about 1 m/s, carried by the wind, fluttering; wrapped in a 16 m box round the eyes (outside the glass).
		FVector P(F.X, F.Y, F.Z);
		P += (Wind * (0.7 + 0.6 * R) + FVector(0.25 * FMath::Sin(F.Z * 3.0 + R * 20.0), 0.25 * FMath::Cos(F.Z * 2.3 + R * 13.0), -0.9 - 0.4 * R)) * DeltaSeconds;
		for (int32 a = 0; a < 3; ++a)
		{
			if (P[a] > 8.0) { P[a] -= 16.0; }
			if (P[a] < -8.0) { P[a] += 16.0; }
		}
		F = FVector4(P.X, P.Y, P.Z, R);
		const bool bIn = FVector2D(P.X, P.Y).Size() < 2.35 && P.Z > -1.7 && P.Z < 1.1;   // not inside the car
		const double S = (i < Shown && !bIn) ? 0.004 + 0.004 * R : 0.0;
		Out[i] = FTransform(FRotator(R * 360.0, R * 720.0, R * 180.0), P * 100.0, FVector(S));
	}
	Flakes->BatchUpdateInstancesTransforms(0, Out, false, true, true);
}

void UJourneyMatterhorn::BuildLake()
{
	// Riffelsee: the lake's outline (the 0.5 m terrain's flat water), fanned from its centre, at its level.
	CubeMesh::FMesh M;
	const int32 N = UE_ARRAY_COUNT(MatterhornData::LakeOutline);
	if (N < 3) { return; }
	FVector2D C(0, 0);
	for (int32 i = 0; i < N; ++i) { C += FVector2D(MatterhornData::LakeOutline[i][0], MatterhornData::LakeOutline[i][1]); }
	C /= N;
	const FVector Up(0, 0, 1);
	auto P = [&](double E, double No) { return FVector(E - C.X, -(No - C.Y), 0.0); };
	const int32 Centre = M.V(P(C.X, C.Y), Up, FVector2D(0, 0));
	TArray<int32> Ring;
	for (int32 i = 0; i < N; ++i)
	{
		const double E = MatterhornData::LakeOutline[i][0], No = MatterhornData::LakeOutline[i][1];
		// 1 m out under the shore, so the water meets the banks with no seam.
		const FVector2D D = (FVector2D(E, No) - C).GetSafeNormal();
		Ring.Add(M.V(P(E + D.X, No + D.Y), Up, FVector2D(E - C.X, No - C.Y)));
	}
	for (int32 i = 0; i < N; ++i) { M.Tri(Centre, Ring[i], Ring[(i + 1) % N]); }
	Lake = NewObject<UProceduralMeshComponent>(Director, MakeUniqueObjectName(Director, UProceduralMeshComponent::StaticClass(), TEXT("Riffelsee")));
	Lake->SetMobility(EComponentMobility::Movable);
	Lake->SetupAttachment(Land);
	Lake->SetCollisionEnabled(ECollisionEnabled::NoCollision);
	Lake->RegisterComponent();
	M.Write(Lake, 0, false);
	UMaterialInterface* Water = LoadObject<UMaterialInterface>(nullptr, TEXT("/Game/Museum/Journeys/Matterhorn/Materials/MI_MH_Lake.MI_MH_Lake"));
	if (!Water) { Water = LoadObject<UMaterialInterface>(nullptr, TEXT("/Game/Museum/Materials/MI_Water_Canal.MI_Water_Canal")); }
	Lake->SetMaterial(0, Water);
	Lake->SetRelativeLocation(FVector(C.X * 100.0, -C.Y * 100.0, MatterhornData::LakeLevel * 100.0));
	JourneyParts.Add(Lake);
}

void UJourneyMatterhorn::PlaceLand(const FView& V)
{
	if (!Pivot || !Land) { return; }
	// The land's point under the eyes: the car's floor, then 1.62 m to the eyes.
	Land->SetRelativeLocation(FVector(-V.E * 100.0, V.N * 100.0, -(V.Floor + 1.62) * 100.0));
	// The Earth's curvature between the summit (taken off in the tiles) and this place: raise the land away from the
	// summit by |V − S| / R per metre (a few hundredths of a degree).
	const FVector2D VS(V.E - MatterhornData::SummitE, V.N - MatterhornData::SummitN);
	const double Dist = VS.Size();
	FQuat Tilt = FQuat::Identity;
	if (Dist > 1.0)
	{
		const FVector U(VS.X / Dist, -VS.Y / Dist, 0.0);   // Unreal's y runs south
		Tilt = FQuat(FVector::CrossProduct(U, FVector::UpVector).GetSafeNormal(), Dist / MatterhornData::REff);
	}
	Pivot->SetRelativeRotation(Tilt);
	// The land within 3 km stays in the near ray-tracing scene (it casts the sun's ray-traced shadows: the Gornergrat's
	// on the Riffelsee at dawn, the ridge's on its faces); beyond, Lumen's far field (reflections and bounce to 10 km).
	const FVector Eye = Director->GetActorLocation();
	for (UStaticMeshComponent* T : Tiles)
	{
		if (!T) { continue; }
		const bool bFar = FMath::Sqrt(T->Bounds.GetBox().ComputeSquaredDistanceToPoint(Eye)) > 300000.0;
		if (T->bRayTracingFarField != bFar) { T->bRayTracingFarField = bFar; T->MarkRenderStateDirty(); }
	}
}

void UJourneyMatterhorn::OpenPlace(int32 Index)
{
	Current = Index;
	const FView& V = View(Index);
	PlaceLand(V);
	if (Land) { Land->SetVisibility(V.bLand, true); }
	if (Index >= 4)
	{
		// The sea of clouds under the summit: an inversion's stratus in the valleys, its top near 3,000 m.
		UVolumetricCloudComponent* Cloud = Make<UVolumetricCloudComponent>(TEXT("CloudSea"));
		Cloud->SetLayerBottomAltitude(1.5f);
		Cloud->SetLayerHeight(2.2f);
		Cloud->SetTracingMaxDistance(120.f);
		Cloud->SetTracingStartMaxDistance(400.f);
		if (UMaterialInterface* M = LoadObject<UMaterialInterface>(nullptr, TEXT("/Game/Museum/Journeys/Matterhorn/Materials/M_MH_CloudSea.M_MH_CloudSea")))
		{
			Cloud->SetMaterial(M);
		}
	}
	if (Index == 1)
	{
		// Inside a crevasse of the Theodul glacier: its walls and the snow over it, the eyes at the origin.
		for (const TCHAR* Name : {TEXT("SM_MH_Crevasse_Walls"), TEXT("SM_MH_Crevasse_Snow")})
		{
			UStaticMesh* Mesh = LoadObject<UStaticMesh>(nullptr, *FString::Printf(TEXT("/Game/Museum/Journeys/Matterhorn/Things/%s.%s"), Name, Name));
			MeshAt(Mesh, FTransform::Identity);
		}
	}
	if (UExponentialHeightFogComponent* Fog = Director->Fog)
	{
		Fog->SetVisibility(false);
		Fog->SetFogMaxOpacity(1.f);
		Fog->SetFogDensity(0.0002f);
		Fog->SetFogHeightFalloff(0.0002f);
		Fog->SetVolumetricFog(true);
		Fog->SetVolumetricFogScatteringDistribution(0.5f);
		Fog->SetVolumetricFogAlbedo(FColor(250, 250, 250));
		Fog->SetVolumetricFogExtinctionScale(1.f);
		Fog->SetFogInscatteringColor(FLinearColor(0.02f, 0.025f, 0.03f));
		Fog->SetStartDistance(0.f);
	}
}

void UJourneyMatterhorn::TickPlace(float DeltaSeconds, double LocalHour, float Fraction, float Veil)
{
	// The ice's glow follows the day (the sun's height at the place: full by mid-morning).
	if (UMaterialParameterCollection* MPC = Director->Parameters())
	{
		const double H = LocalHour;
		const float Day = float(FMath::Clamp((H - 5.5) / 3.0, 0.0, 1.0) * FMath::Clamp((21.5 - H) / 3.0, 0.0, 1.0));
		UKismetMaterialLibrary::SetScalarParameterValue(Director, MPC, TEXT("IceGlow"), Day);
	}
	// Snow: at the end of the night it snows inside the Cube, thickening to white; on the ridge, spindrift.
	if (Current == 5) { MoveFlakes(DeltaSeconds, FMath::Clamp((Fraction - 0.55f) / 0.35f, 0.f, 1.f), FVector(0.6, 0.3, 0)); }
	else if (Current == 3) { MoveFlakes(DeltaSeconds, 0.12f + 0.1f * FMath::Sin(float(LocalHour) * 40.f), FVector(-7.0, 3.0, 1.0)); }
	else if (Flakes) { Flakes->SetVisibility(false); }
	// Zermatt's lights come on at dusk.
	if (Lamps)
	{
		const float Night = float(FMath::Clamp((LocalHour - 21.0) / 0.7, 0.0, 1.0));
		Lamps->SetVisibility(Night > 0.01f);
		if (LampGlow) { LampGlow->SetScalarParameterValue(TEXT("Nits"), 250.f * Night); }
	}
	// The cloud between places: the fog thickens round the car until it is white, and clears on the next place.
	if (UExponentialHeightFogComponent* Fog = Director->Fog)
	{
		const float V = Veil * Veil;
		// Only the veil: a height fog left on would lie over the sky too (flat, one colour); the atmosphere's own
		// aerial perspective hazes the land.
		Fog->SetVisibility(V > 0.001f);
		Fog->SetFogDensity(FMath::Lerp(0.0002f, 0.9f, V));
		Fog->SetFogHeightFalloff(FMath::Lerp(0.0002f, 0.00001f, V));
		Fog->SetVolumetricFogExtinctionScale(FMath::Lerp(1.f, 4.f, V));
	}
}

void UJourneyMatterhorn::Teardown()
{
	Super::Teardown();
	if (IConsoleVariable* Far = IConsoleManager::Get().FindConsoleVariable(TEXT("r.LumenScene.FarField")))
	{
		if (FarFieldWas >= 0 && Far->GetInt() != FarFieldWas) { Far->Set(FarFieldWas, ECVF_SetByCode); }
	}
	Tiles.Reset();
	Pivot = nullptr;
	Land = nullptr;
	Lake = nullptr;
	Lamps = nullptr;
	LampGlow = nullptr;
	Flakes = nullptr;
	FlakeState.Reset();
}
